# Use : docker-compose run app ts-node app/console script:run Sample/Allocine/AllocineCinemas

app:
  build: .
  links:
    - db
  environment:
    MONGO_HOST: db_1
    MONGO_PORT: 27043
  volumes:
      - ./src:/opt/soft/src
      - ./vendor:/opt/soft/vendor
      - ./app/config:/opt/soft/app/config

db:
  image: mongo
  command: "mongod --port=27043 --smallfiles --logpath=/dev/null"